# Generated by Django 6.0.3 on 2026-04-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=20)),
                ('region_name', models.CharField(max_length=100)),
                ('parameter_code', models.CharField(max_length=20)),
                ('parameter_name', models.CharField(max_length=100)),
                ('order_type', models.CharField(choices=[('date', 'Date'), ('ranked', 'Ranked')], max_length=10)),
                ('source_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('series_start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_updated_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('region_code', 'parameter_code', 'order_type')},
            },
        ),
        migrations.CreateModel(
            name='ClimateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('jan', models.FloatField(blank=True, null=True)),
                ('feb', models.FloatField(blank=True, null=True)),
                ('mar', models.FloatField(blank=True, null=True)),
                ('apr', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('jun', models.FloatField(blank=True, null=True)),
                ('jul', models.FloatField(blank=True, null=True)),
                ('aug', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('oct', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('win', models.FloatField(blank=True, null=True)),
                ('spr', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('aut', models.FloatField(blank=True, null=True)),
                ('ann', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='climate.climatedataset')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('dataset', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ClimateRankedStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_code', models.CharField(max_length=10)),
                ('rank', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_stats', to='climate.climatedataset')),
            ],
            options={
                'ordering': ['period_code', 'rank'],
                'indexes': [models.Index(fields=['dataset', 'period_code'], name='climate_cli_dataset_c43ad8_idx')],
                'unique_together': {('dataset', 'period_code', 'rank')},
            },
        ),
    ]
